name: Trigger Remote Workflow
on:
  release:
    types:
      - published

jobs:
  trigger-remote-workflow:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read Swagger version and title
        id: swagger_info
        run: |
          VERSION=$(grep 'version:' swagger.yaml | awk '{print $2}' | tr -d '\r\n' | xargs)
          TITLE=$(awk '/^info:/ {found=1} found && /title:/ {sub(/title: /, ""); print; exit}' swagger.yaml | tr -d '\r\n' | xargs)
          echo "Swagger version: $VERSION"
          echo "Swagger title: $TITLE"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "TITLE=$TITLE" >> $GITHUB_ENV

      - name: Trigger remote workflow with JSON debug
        env:
          VERSION: ${{ env.VERSION }}
          TITLE: ${{ env.TITLE }}
        run: |
          JSON=$(printf '{
            "ref": "main",
            "inputs": {
              "repository": "%s",
              "branch": "%s",
              "version": "%s",
              "title": "%s",
              "pr_number": "%s"
            }
          }' \
          "${{ github.repository }}" \
          "${{ github.event.pull_request.base.ref }}" \
          "$VERSION" \
          "$TITLE" \
          "${{ github.event.pull_request.number }}")

          echo "üîç JSON final a ser enviado:"
          echo "$JSON"

          curl -X POST -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.REPO_ACCESS_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "$JSON" \
            "https://api.github.com/repos/OpenBanking-Brasil/CI-CD-OFB/actions/workflows/tag-control.yml/dispatches"
